### ISSUE TITLE
Multiple scattering calculation errors sometimes for certain energies

### ISSUE THREAD

**Issue by DanPorter** [DanPorter/Dans_Diffraction#19]
Whilst running some multiple scatter simulations (attached), an error appears stopping the simulation:
```
Traceback (most recent call last):
  File "C:\Users\grp66007\OneDrive - Diamond Light Source Ltd\PythonProjects\Dans_Diffraction\Test\U3O8_multiple_scattering.py", line 15, in <module>
    u3o8.Plot.plot_ms_azimuth([0, 0, 2], 3.726, [1, 0, 0], [1, 0])
  File "C:\Users\grp66007\OneDrive - Diamond Light Source Ltd\PythonProjects\Dans_Diffraction\Dans_Diffraction\classes_plotting.py", line 1355, in plot_ms_azimuth
    azimuth, intensity = self.xtl.Scatter.ms_azimuth(hkl, energy_kev, azir, pv, numsteps, peak_width,
  File "C:\Users\grp66007\OneDrive - Diamond Light Source Ltd\PythonProjects\Dans_Diffraction\Dans_Diffraction\classes_scattering.py", line 2498, in ms_azimuth
    azimuth = np.concatenate(mslist[:, [3, 4]])
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```
Python version: 3.8.19
Numpy version: 1.24.3

This error does not appear in later versions of Numpy and Python.

[multiple_scattering_error.zip](https://github.com/user-attachments/files/16408799/multiple_scattering_error.zip)

**Comment by DanPorter** [comment]
This error originates from the multiple_scattering/run_calcms function returning an empty list. The list is empty because of NaN values produced in the call to Calcms.sfonly():
https://github.com/DanPorter/Dans_Diffraction/blob/4665a159bc8704f3a027ca5c861b5336fb48d07e/Dans_Diffraction/multiple_scattering.py#L116-L117

Tracking the nan values through the code, they appear to originate from a call to np.empty to pre-allocate an array for Bragg angles:
https://github.com/DanPorter/Dans_Diffraction/blob/4665a159bc8704f3a027ca5c861b5336fb48d07e/Dans_Diffraction/multiple_scattering.py#L367-L369

This explains the strange behaviour as np.empty pre-allocates different values depending on things like operating system and processor and is not recommended for assignment purposes.
Switching from np.empty to np.ones fixes the issue:
``` python
brag1 = Bragg(self.lattice, self.hkl, self.energy).th() * np.ones(len(self.hkl2))
```
