### ISSUE TITLE
support mcif

### ISSUE THREAD

**Issue by dragonyanglong** [DanPorter/Dans_Diffraction#27]
Hi @DanPorter , does this software support using a .mcif as input?

**Comment by DanPorter** [comment]
Hi @dragonyanglong, 

Yes, Dans_Diffraction will read mcif files. It will also write the files in most cases as well. Please see the following example: 

https://github.com/DanPorter/Dans_Diffraction/blob/master/Examples/example_magnetic_cif.py

**Comment by dragonyanglong** [comment]
Dear @DanPorter , Thanks so much for your reply. I tried the `neutron` and `neutron magnetic` powder pattern simulation. The `neutron` looks good, but the `neutron magnetic ` seems like incorrect. I take the `1.31_MnO.mcif` from Bilbao magnetic server as an example (I added .txt extension to upload here in case someone want to reproduce. It should have **Q = 1.2 A-1** magnetic bragg peak, but not shown in the simulation. I attach the codes as below. What ?
[1.31_MnO.mcif.txt](https://github.com/user-attachments/files/18134132/1.31_MnO.mcif.txt)


Neutron: Result is correct.
```
import sys,os
import numpy as np
import matplotlib.pyplot as plt
import Dans_Diffraction as dif

f1 = '1.31_MnO.mcif'
xtl = dif.Crystal(f1)

energy_kev = dif.fc.wave2energy(1.5498)
max_twotheta = 180
xtl.Scatter.setup_scatter('neutron') 
q, intensity, reflections = xtl.Scatter.powder(scattering_type='neutron ', units='Q', energy_kev=energy_kev, peak_width=0.01, background=0)

plt.figure()
plt.plot(q, intensity, '-', lw=2)
dif.fp.labels('neutron powder diffraction MnO', 'Q ($\AA^{-1}$)', 'intensity')
plt.show()
```
![neutron_MnO](https://github.com/user-attachments/assets/4b2f7fe4-7379-477e-996c-76ba70fb82f9)



Neutron magnetic: Result is incorrect.
```
import sys,os
import numpy as np
import matplotlib.pyplot as plt
import Dans_Diffraction as dif

f1 = '1.31_MnO.mcif'
xtl = dif.Crystal(f1)

energy_kev = dif.fc.wave2energy(1.5498)
max_twotheta = 180
xtl.Scatter.setup_scatter('neutron magnetic') 
q, intensity, reflections = xtl.Scatter.powder(scattering_type='neutron magnetic', units='Q', energy_kev=energy_kev, peak_width=0.01, background=0)

plt.figure()
plt.plot(q, intensity, '-', lw=2)
dif.fp.labels('neutron magnetic powder diffraction MnO', 'Q ($\AA^{-1}$)', 'intensity')
plt.show()
```

![neutron_mag_MnO](https://github.com/user-attachments/assets/0619a33f-f083-4957-921d-626413879ce3)

**Comment by DanPorter** [comment]
Hi @dragonyanglong,

Apologies for the slow reply, this is an interesting observation!

The lack of a peak at Q=1.2A-1 comes from the magnetic intensity of the (111) reflection being zero. This is not what you would expect looking at the structure of MnO, so I had a closer look at the calculation.

It turns out, the structure factor of (111) is non-zero, but depending on the polarisation of the incident beam, the structure factor is positive or negative, and therefore when I average the polarisations in the calculation, the sum is zero.

There is a way to use a non-averaged polarisation in the code at the moment, but it is quite hidden, so I will add some additional options to make this easier to use.

**Comment by dragonyanglong** [comment]
Thanks for looking into this. BTW, I tried GSAS-II scriptable code to simulate neutron magnetic Bragg peak of MnO, and it gives the correct signals (with Q=1.2A-1 magnetic bragg peak) as experimental data.

**Comment by DanPorter** [comment]
Hi @dragonyanglong, 

I've created a new branch with options to used polarised neutrons, here is an example:
```python
f = 'MnO.mcif'

xtl = dif.Crystal(f)

wl = 1.5498
options = {
    'units': 'Q',
    'wavelength_a': wl,
    'peak_width': 0.02,
    'background': 0,
}
xtl.Scatter.setup_scatter(max_twotheta=40, output=False)

q1, intensity1, reflections1 = xtl.Scatter.powder(scattering_type='neutron', **options)
q2, intensity2, reflections2 = xtl.Scatter.powder(scattering_type='neutron magnetic', **options)
xtl.Scatter.setup_scatter(polarisation_vector=[1, 0, 0])
q3, intensity3, reflections3 = xtl.Scatter.powder(scattering_type='neutron polarised', **options)
xtl.Scatter.setup_scatter(polarisation_vector=[0, 0, 1])
q4, intensity4, reflections4 = xtl.Scatter.powder(scattering_type='neutron polarised', **options)

plt.figure(figsize=[14, 8], dpi=60)
plt.plot(q1, intensity1, '-', lw=2, label='neutron')
plt.plot(q2, intensity2, '-', lw=2, label='neutron magnetic')
plt.plot(q3, intensity3, '-', lw=2, label='neutron polarised || a*')
plt.plot(q4, intensity4, '-', lw=2, label='neutron polarised || c*')
dif.fp.labels('neutron powder diffraction MnO', 'Q ($\AA^{-1}$)', 'intensity', legend=True)

plt.show()
```

![MnO_neutron_polarised](https://github.com/user-attachments/assets/d14e2608-0799-4ce4-be96-c841912a6c7c)

I'll still need to look at how to get the un-polarised magnetic scattering to work correctly, but hopefully this will help!

I'll aim to merge the branch into main in a couple of weeks, but please let me know if you have any comments.

**Comment by DanPorter** [comment]
Hi @dragonyanglong, 

I've now merged the changed into the main branch. I've removed the old way I did unpolarised magnetic calculations and the standard polarised approach is now standard. I believe this should agree with GSAS-II.

Thanks again for raising this issue.

Any other problems or comments, let me know! 

Dan

**Comment by dragonyanglong** [comment]
Hi @DanPorter , thanks for updating the codes to support this. I tried to do testing, but I cannot import the package now, `import Dans_Diffraction as dif` gives error as follows. I installed `Dans-Diffraction-3.3.3`:

```
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    import Dans_Diffraction as dif
  File "/Users/longyang/Documents/Tongji/dev/Dans_Diffraction/Dans_Diffraction/__init__.py", line 154, in <module>
    from . import functions_plotting as fp
  File "/Users/longyang/Documents/Tongji/dev/Dans_Diffraction/Dans_Diffraction/functions_plotting.py", line 49, in <module>
    from . import functions_crystallography as fc
  File "/Users/longyang/Documents/Tongji/dev/Dans_Diffraction/Dans_Diffraction/functions_crystallography.py", line 64, in <module>
    from . import functions_lattice as fl
  File "/Users/longyang/Documents/Tongji/dev/Dans_Diffraction/Dans_Diffraction/functions_lattice.py", line 342
    while not angles_allowed(*(triclinic_angles := [rang(), rang(), rang()])):
                                                ^
SyntaxError: invalid syntax
```

**Comment by DanPorter** [comment]
Hi @dragonyanglong,

I can't reproduce your error at my end using python 3.12, which python version are you using?

**Comment by DanPorter** [comment]
Ah, the "Walrus operator" as implemented in Python 3.8 and seems to be the error here. You will be able to get the code to work using any version of python >= 3.8.
For greater compatibility I'll remove it in the next release.

**Comment by dragonyanglong** [comment]
I see. I tried python 3.11 and it works great for the neutron magnetic simulation! Thanks so much!
